import JSZip from "jszip";
import { Content, RenderResult, StyleModule } from "../types";
import { ImageLoader } from "./image";

export function generateHowToPublishMd(handle: string): string {
  return `# How to Publish Your Profile README

1. **Create your Profile Repository**:
   - Go to GitHub and create a **PUBLIC** repository named exactly \`${handle}\`.
   - Ensure the repository name matches your username exactly.

2. **Add Files**:
   - Copy \`README.md\` to the root of your repository.
   - Copy the entire \`assets/\` folder to the root of your repository.
   - Commit and push to your \`main\` branch.

3. **Check Theme & Links**:
   - Verify that your LinkedIn link has been updated (replace placeholder if not done).
   - Check your profile in both GitHub Light and Dark modes.

4. **Reduced Motion**:
   - Viewers who enable "prefers-reduced-motion" in their OS or browser settings will automatically see static SVGs without animation.
`;
}

export function generateArtworkNotesTxt(style: StyleModule): string {
  return `ARTWORK NOTES & CREDITS
Style: ${style.name} (${style.id})
Credit: ${style.image?.credit || "Procedural / Original Design"}
Note: ${style.image?.note || "Ensure you have the right to display custom imagery on your public GitHub profile."}
`;
}

export async function createStyleZip(
  style: StyleModule,
  content: Content,
  result: RenderResult
): Promise<Blob> {
  const zip = new JSZip();
  const folder = zip.folder(`${content.handle}-${style.id}`) || zip;

  folder.file("README.md", result.readme);
  folder.file("content.json", JSON.stringify(content, null, 2));
  folder.file("HOW-TO-PUBLISH.md", generateHowToPublishMd(content.handle));
  folder.file("ARTWORK-NOTES.txt", generateArtworkNotesTxt(style));

  const assetsFolder = folder.folder("assets");
  if (assetsFolder) {
    for (const [name, svg] of Object.entries(result.files)) {
      assetsFolder.file(name, svg);
    }
  }

  return await zip.generateAsync({ type: "blob" });
}

export async function createAllStylesZip(
  styles: StyleModule[],
  content: Content,
  onProgress?: (percent: number, current: string) => void
): Promise<Blob> {
  const zip = new JSZip();
  const root = zip.folder(`${content.handle}-readme-collection`) || zip;

  let indexMd = `# ${content.name} — README Styles Collection\n\n`;
  indexMd += `Collection of ${styles.length} themes generated by Profile Atelier.\n\n`;

  for (let i = 0; i < styles.length; i++) {
    const s = styles[i];
    if (onProgress) {
      onProgress(Math.round((i / styles.length) * 100), s.name);
    }

    const res = await s.render(content, ImageLoader);
    const sFolder = root.folder(s.id);
    if (sFolder) {
      sFolder.file("README.md", res.readme);
      sFolder.file("HOW-TO-PUBLISH.md", generateHowToPublishMd(content.handle));
      sFolder.file("ARTWORK-NOTES.txt", generateArtworkNotesTxt(s));
      const sAssets = sFolder.folder("assets");
      if (sAssets) {
        for (const [name, svg] of Object.entries(res.files)) {
          sAssets.file(name, svg);
        }
      }
    }
    indexMd += `- [${s.name}](./${s.id}/README.md) (${s.keywords.join(", ")})\n`;
  }

  root.file("README.md", indexMd);
  root.file("content.json", JSON.stringify(content, null, 2));

  if (onProgress) onProgress(100, "Finalizing ZIP package...");
  return await zip.generateAsync({ type: "blob" });
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
